addons:
  sauce_connect:
    username: "karlitowhoelse"
    access_key: "d45485e6-5775-4719-b001-c2c4409feae6"
deploy:
  default: true
  keyfile: Cook AdLib-629247c92d53.json
  on:
    branch: master
    tags: true
  project: cook-adlib
  provider: gae
  skip_cleanup: true
before_install:
- openssl aes-256-cbc -K $encrypted_b34ad3c3bd8d_key -iv $encrypted_b34ad3c3bd8d_iv
  -in Cook\ AdLib-629247c92d53.json.enc -out Cook\ AdLib-629247c92d53.json -d
before_script:
  # - npm install -g babel-core
  # - npm install -g babel-eslint
  # - npm install -g eslint
  # - npm install -g gulp
script: gulp build
language: node_js
node_js:
  - "4.1"
