deploy:
  default: true
  keyfile: Cook AdLib-629247c92d53.json
  on: production
  project: cook-adlib
  provider: gae
  skip_cleanup: true
before_install:
- openssl aes-256-cbc -K $encrypted_b34ad3c3bd8d_key -iv $encrypted_b34ad3c3bd8d_iv
  -in Cook\ AdLib-629247c92d53.json.enc -out Cook\ AdLib-629247c92d53.json -d
before_script:
  # - npm install -g babel-core
  # - npm install -g babel-eslint
  # - npm install -g eslint
  # - npm install -g gulp
script: gulp build
language: node_js
node_js:
  - "4.1"
