'use strict';

export {default as bower} from './tasks/bower';
// export {default as browserSync} from './tasks/browser-sync';
// export {default as cacheClear} from './tasks/cache-clear';
// export {default as cacheConfig} from './tasks/cache-config';
// export {default as check} from './tasks/check';
// export {default as clean} from './tasks/clean';
// export {default as copy} from './tasks/copy';
// export {default as deploy} from './tasks/deploy';
// export {default as documentation} from './tasks/documentation';
// export {default as fonts} from './tasks/fonts';
// export {default as framework} from './tasks/framework';
// export {default as icons} from './tasks/icons';
// export {default as images} from './tasks/images';
// export {default as locales} from './tasks/locales';
// export {default as markup} from './tasks/markup';
// export {default as pagespeed} from './tasks/pagespeed';
// export {default as removeOldBuildIndex} from './tasks/remove-old-build-index';
// export {default as renameIndex} from './tasks/rename-index';
// export {default as renameSpritesheet} from './tasks/rename-spritesheet';
// export {default as rsync} from './tasks/rsync';
// export {default as sassForBrowser} from './tasks/sass-for-browser';
// export {default as scraper} from './tasks/scraper';
// export {default as screenshots} from './tasks/screenshots';
// export {default as scripts} from './tasks/scripts';
// export {default as server} from './tasks/server';
// export {default as sounds} from './tasks/sounds';
// export {default as styleguide} from './tasks/styleguide';
// export {default as styles} from './tasks/styles';
// export {default as symlinks} from './tasks/symlinks';
// export {default as tag} from './tasks/tag';
// export {default as templates} from './tasks/templates';
// export {default as test} from './tasks/test';
// export {default as videos} from './tasks/videos';
// export {default as vulcanize} from './tasks/vulcanize';
