'use strict';

export {watch as bower} from './tasks/bower';
export {watch as browserSync} from './tasks/browser-sync';
export {watch as cacheClear} from './tasks/cache-clear';
export {watch as cacheConfig} from './tasks/cache-config';
// export {watch as check} from './tasks/check';
// export {watch as clean} from './tasks/clean';
export {watch as copy} from './tasks/copy';
export {watch as documentation} from './tasks/documentation';
export {watch as fonts} from './tasks/fonts';
export {watch as framework} from './tasks/framework';
export {watch as icons} from './tasks/icons';
export {watch as images} from './tasks/images';
export {watch as locales} from './tasks/locales';
export {watch as markup} from './tasks/markup';
export {watch as pagespeed} from './tasks/pagespeed';
export {watch as removeOldBuildIndex} from './tasks/remove-old-build-index';
export {watch as renameIndex} from './tasks/rename-index';
export {watch as renameSpritesheet} from './tasks/rename-spritesheet';
export {watch as rsync} from './tasks/rsync';
export {watch as sassForBrowser} from './tasks/sass-for-browser';
export {watch as scraper} from './tasks/scraper';
export {watch as screenshots} from './tasks/screenshots';
export {watch as scripts} from './tasks/scripts';
export {watch as server} from './tasks/server';
export {watch as sounds} from './tasks/sounds';
export {watch as styleguide} from './tasks/styleguide';
export {watch as styles} from './tasks/styles';
export {watch as symlinks} from './tasks/symlinks';
export {watch as tag} from './tasks/tag';
export {watch as templates} from './tasks/templates';
export {watch as test} from './tasks/test';
export {watch as videos} from './tasks/videos';
export {watch as vulcanize} from './tasks/vulcanize';
